# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Minsoo.LIM history
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/Minsoo_port" # the subpath of the site
url: "https://minzlim.github.io/" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Project List
      slug: /
    - name: Certification

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: mslim0202@hanmail.net
      link: mailto:mslim0202@hanmail.net
  follow:
    - name: Facebook
      link: https://www.facebook.com/profile.php?id=100004460649902

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
